apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../remote-helm-kustomize

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: release-name-wordpress
  patch: |
    - op: replace
      path: /spec/replicas
      value: 0
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: release-name-mariadb
  patch: |
    - op: replace
      path: /spec/replicas
      value: 0
