apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../remote-helm-kustomize

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: release-name-wordpress
