apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# helmGlobals:
  # chartHome: ../

helmCharts:
  - name: wordpress
    version: 9.0.3
    repo: https://charts.helm.sh/stable
    valuesFile: values-fz1.yaml
