apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../

helmCharts:
  - name: helm-guestbook
    valuesFile: values-overwrite.yaml
    # releaseName: guestbook
    # namespace: default
    # version: 0.1.0
    # valuesFile: values.yaml
