apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../helm-guestbook

helmCharts:
  - name: helm-guestbook
    releaseName: guestbook
    namespace: default
    version: 0.1.0
    valuesFile: values.yaml
